[project]
name = "ckanext-ghoharvester"
version = "0.1.0"
description = "Harvester a medida para la API OData del Global Health Observatory (OMS), para DATAlife"
requires-python = ">=3.9"
dependencies = [
  "ckantoolkit",
  "requests",
]

[project.entry-points."ckan.plugins"]
gho_harvester = "ckanext.ghoharvester.plugin:GHOHarvester"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ckanext*"]
